on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Select environments
        uses: dawsonone/multi-select@v4
        id: select_env
        with:
          title: 'Select environments to deploy'
          options: 'dev,staging,technical'
          default: 'dev'  # Optional: Pre-select 'dev' by default

      - name: Run deployment for selected environments
        run: |
          echo "Deploying to environments: ${{ steps.select_env.outputs.selectedOptions }}"
          # Add your deployment logic here, using the selected environments
          # This part will likely involve conditional checks based on the selected options
          if [[ ${{ steps.select_env.outputs.selectedOptions }} == *"dev"* ]]; then
              # Perform deployment steps for dev environment
          fi
          if [[ ${{ steps.select_env.outputs.selectedOptions }} == *"staging"* ]]; then
              # Perform deployment steps for staging environment
          fi
          if [[ ${{ steps.select_env.outputs.selectedOptions }} == *"technical"* ]]; then
              # Perform deployment steps for technical environment
          fi
