name: Manual Deploy to Remote Server

on:
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Select job to executee'
        required: true
        options:
          - 'deploy'

jobs:
  deploy:
    runs-on: self-hosted
    #if: ${{ github.ref == 'refs/heads/upgrade_rails_version' }}
  
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            /srv/www/altagem/script/deploy.sh
          command_timeout: 26m 



# name: Manual triggers

# on:
#   workflow_dispatch:
#     inputs:
#       withBackup:
#         description: "Do you need to use a specified company database?"
#         required: true
#         type: "choice"
#         options:
#           - "yes"
#           - "no"
#       DatabaseName:
#         description: "Name of the database"
#         required: false
#         type: "string"
# #  push:
# #    branches:
# #      - feature/dockerisation

# jobs:
#   hello:
#     runs-on: self-hosted

#     steps:
#       - name: Display Inputs
#         run: |
#           echo "Do you need to use a specified company database? ${{ github.event.inputs.withBackup }}"
#           echo "Name of the database: ${{ github.event.inputs.DatabaseName }}"
