on:
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Select job to execute'
        required: true
        options:
          - 'dev'
          - 'staging'
          - 'technical'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set job name
        run: echo "Job Name: ${{ github.event.inputs.job_name }}"

      - name: Execute job0
        if: ${{ github.event.inputs.job_name == 'dev' }}
        run: |
          echo "Executing development job"
          # Add commands for the development job here

      - name: Execute job1
        if: ${{ github.event.inputs.job_name == 'staging' }}
        run: |
          echo "Executing staging job"
          # Add commands for the staging job here

      - name: Execute job2
        if: ${{ github.event.inputs.job_name == 'technical' }}
        run: |
          echo "Executing technical job"
          # Add commands for the technical job here
