on:
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Select job to execute'
        required: true
        type: choice
        options:
          - 'dev'
          - 'staging'
          - 'technical'
      sqlite:
        description: 'Select job to sqlite'
        required: true
        type: choice
        options:
          - 'v1'
          - 'v2'
      company:
        description: 'add company name or less vide for all companies'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  # Indentation fixed here (one level)
        uses: actions/checkout@v2

      # Other steps remain the same (indentation already correct)
      - name: Set job name
        run: echo "${{ github.event.inputs.job_name }}"

      - name: Execute development job
        if: ${{ github.event.inputs.job_name == 'dev' }}
        run: |
          echo "Executing development job"
          echo ${{ github.event.inputs.sqlite  }}
          echo ${{ github.event.inputs.company  }}

      - name: Execute staging job
        if: ${{ github.event.inputs.job_name == 'staging' }}
        run: |
          echo "Executing staging job"
          # Add commands for the staging job here

      - name: Execute technical job
        if: ${{ github.event.inputs.job_name == 'technical' }}
        run: |
          echo "Executing technical job"
          # Add commands for the technical job here

